config/routes.rb
Rails.application.routes.draw do
  #devise_for :models
  devise_for :users
  resources :phone_numbers
  resources :address_details
  resources :contact_names
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact_name.rb
class ContactName < ApplicationRecord
  has_many :address_details, dependent: :destroy
  has_many :phone_numbers, dependent: :destroy
  accepts_nested_attributes_for :address_details ,allow_destroy: true
  accepts_nested_attributes_for :phone_numbers, allow_destroy: true
  validates :firstName, :lastName, :email, presence: true
  validates_associated :address_details,presence: true
  validates_associated :phone_numbers,presence: true
end

app/controllers/contact_names_controller.rb
class ContactNamesController < ApplicationController
  before_action :set_contact_name, only: [:show, :edit, :update, :destroy]

  # GET /contact_names
  # GET /contact_names.json
  def index
    @contact_names = ContactName.all
  end

  # GET /contact_names/1
  # GET /contact_names/1.json
  def show
    if @contact_name.blank?
      redirect_to action: 'index'
    else
      @contact_name = ContactName.where("id=?",@contact_name.id).includes(:address_details,:phone_numbers)
    end
  end

  # GET /contact_names/new
  def new
    @contact_name = ContactName.new
    @contact_name.address_details.new
    @contact_name.phone_numbers.new
  end

  # GET /contact_names/1/edit
  def edit
  end

  # POST /contact_names
  # POST /contact_names.json
  def create
    @contact_name = ContactName.new(contact_name_params)
    respond_to do |format|
      if @contact_name.save
        format.html { redirect_to @contact_name, notice: 'Contact name was successfully created.' }
        format.json { render :show, status: :created, location: @contact_name }
      else
        format.html { render :new }
        format.json { render json: @contact_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_names/1
  # PATCH/PUT /contact_names/1.json
  def update
    respond_to do |format|
      if @contact_name.update(contact_name_params)
        format.html { redirect_to @contact_name, notice: 'Contact name was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_name }
      else
        format.html { render :edit }
        format.json { render json: @contact_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_names/1
  # DELETE /contact_names/1.json
  def destroy
    @contact_name.destroy
    respond_to do |format|
      format.html { redirect_to contact_names_url, notice: 'Contact name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_name
      if params[:id] == "contact_names"
      @contact_name =[]
      else  
      @contact_name = ContactName.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_name_params
      params.require(:contact_name).permit(:firstName, :lastName, :email,address_details_attributes:[:id,:address_text,:pincode,:city_name,:state_name,:country_name,:_destroy],phone_numbers_attributes:[:id,:contact_number,:_destroy])
    end
end

app/helpers/contact_names_helper.rb
module ContactNamesHelper
end

app/views/contact_names/_address_detail_fields.html.erb
<style>
	a[href="#"], a[href=""] {
    cursor: default;
}
</style>
<fieldset>
<div class="container-fluid" >
	<div class="row">
		<div class="col-md-12">
	    	<div class="form-group">
	    		<%= f.label :address %>
	   			<%= f.text_area :address_text , :placeholder => 'Address,Street/Area',class: "form-control" ,maxlength: "40"%>
	    	</div>
			<div class="form-group">
				<%= f.label :pincode %>
	   			<%= f.text_field :pincode, class: "form-control" , onkeypress:"return isNumberKey(event);", maxlength: "6"%>
			</div>
			<div class="form-group">
				<%= f.label :city %>
	   			<%= f.text_field :city_name, class: "form-control",maxlength: "20" %>
			</div>
			<div class="form-group">
				<%= f.label :state %>
	   			<%= f.text_field :state_name, class:"form-control",maxlength: "25"%>
			</div>
			<div class="form-group">
				<%= f.label :country %>
	   			<%= f.text_field :country_name, class:"form-control",maxlength: "20"%>
			</div>
			<div class="form-group">
				<%= f.hidden_field :_destroy %>
			</div>
			<div class="form-group">
				<%= link_to "Remove", '#', class: "remove_fields" %>
			</div>
		</div>
	</div>
</div>
</fieldset>
<div class="modal fade modal-confirm" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
          <div class="modal-body">
              <i class="md md-alert-circle" style="font-size: 60px;"></i>
              <h3 class="modal-confirm-message"><span id="alertMsg" style="font-size: 18px;"></span></h3>
              <button type="button" data-dismiss="modal" class="btn btn-lg">Ok</button>
          </div>
      </div>
  </div>
</div>
<% content_for(:extra_scripts) do %>
	function isNumberKey(evt) {
	var charCode = (evt.which) ? evt.which : event.keyCode;
	if (charCode > 31 && ((charCode < 48) || (charCode > 57))){
		displayAlertMsg("Only numeric");
		return false;
	}
	return true;
}

function displayAlertMsg(alertMsg) {
    $("#alertModal").modal('show');
    $("#alertMsg").text(alertMsg);
}
<% end %>
	    		
	    		
	    
		

app/views/contact_names/_form.html.erb
<style>
	a[href="#"], a[href=""] {
    cursor: default;
}
</style>
<%= form_for contact_name do |form| %>
  <% if contact_name.errors.any? %>
    <div id="error_explanation">
	      <h2><%= pluralize(contact_name.errors.count, "error") %> prohibited this contact_name from being saved:</h2>
	      <ul>
	      <% contact_name.errors.full_messages.each do |message| %>
	        <li><%= message %></li>
	      <% end %>
	      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :firstName %>
    <%= form.text_field :firstName, id: :contact_name_firstName,class:"form-control"  %>
  </div>

  <div class="form-group"">
    <%= form.label :lastName %>
    <%= form.text_field :lastName, id: :contact_name_lastName,class:"form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_name_email,class:"form-control"  %>
  </div>
  Address Details:
  <div class="form-group">
  	<%= form.fields_for :address_details do |f| %>
			 <%= render 'address_detail_fields' , f: f%>
	<%end%>
	<%= link_to_add_fields 'Add Address', form,:address_details%>
  </div>
  Contact Phone Numbers:
  <div class="form-group">
  	<%= form.fields_for :phone_numbers do |f| %>
			 <%= render 'phone_number_fields' , f: f%>
	<%end%>
	<%= link_to_add_fields 'Add Phone Number', form,:phone_numbers%>
  </div>

  <div class="form-buttons">
    <%= form.submit(class:"btn btn-default") %>
  </div>
<% end %>
		

app/views/contact_names/_phone_number_fields.html.erb
<style>
	a[href="#"], a[href=""] {
    cursor: default;
}
</style>
<fieldset>
<div class="container-fluid" >
	<div class="row">
		<div class="col-md-12">
			<div class="form-group">
			    <tr>
			    	<td>
			    		<%= f.label :phone_number %>
			   			<%= f.telephone_field :contact_number  ,class: "form-control" , onkeypress:"return isNumberKey(event);",maxlength: "10" %>
						<%= f.hidden_field :_destroy %>
						<%= link_to "Remove Phone Number", '#', class: "remove_fields" %>
			    	</td>
				</tr>
			</div>
		</div>
	</div>
</div>
</fieldset>
<div class="modal fade modal-confirm" id="alertModal" tabindex="-1" role="dialog" aria-labelledby="confirmModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
      <div class="modal-content">
          <div class="modal-body">
              <i class="md md-alert-circle" style="font-size: 60px;"></i>
              <h3 class="modal-confirm-message"><span id="alertMsg" style="font-size: 18px;"></span></h3>
              <button type="button" data-dismiss="modal" class="btn btn-lg">Ok</button>
          </div>
      </div>
  </div>
</div>
<% content_for(:extra_scripts) do %>
	function isNumberKey(evt) {
	var charCode = (evt.which) ? evt.which : event.keyCode;
	if (charCode > 31 && ((charCode < 48) || (charCode > 57))){
		displayAlertMsg("Only numeric");
		return false;
	}
	return true;
}

function displayAlertMsg(alertMsg) {
    $("#alertModal").modal('show');
    $("#alertMsg").text(alertMsg);
}
<% end %>

app/views/contact_names/edit.html.erb
<h1>Editing Contact Name</h1>

<%= render 'form', contact_name: @contact_name %>

<%= link_to 'Show', @contact_name %> |
<%= link_to 'Back', contact_names_path %>

app/views/contact_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Names</h1>

<table class="display table table-striped table-sm table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Email</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @contact_names.each do |contact_name| %>
      <tr>
        <td><%= contact_name.firstName %></td>
        <td><%= contact_name.lastName %></td>
        <td><%= contact_name.email %></td>
        <td><%= link_to 'Show', contact_name %></td>
        <td><%= link_to 'Edit', edit_contact_name_path(contact_name) %></td>
        <td><%= link_to 'Destroy', contact_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact Name', new_contact_name_path %>

app/views/contact_names/new.html.erb
<% content_for :action_buttons do %>
<div class="input-group">
</div>
<% end %>
<div class="container-fluid" >
	<div class="row">
		<div class="col-lg-9">
			<div class="panel panel-default">
				 <div class="panel-heading ">
					<h2>New Contact Name</h2>
				</div>
				 <div class=panel-body>
					<%= render 'form', contact_name: @contact_name %>
					<%= link_to 'Back', contact_names_path %>
				</div>
			</div>
		</div>
	</div>
</div>
<% content_for(:extra_scripts) do %>
	
<%end%>
	

app/views/contact_names/show.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-md-12">
			<% content_for(:page_header) do %>
			Contact Show
			<% end %>
		  <table id="contact_list" class="display table table-striped table-sm table-hover" cellspacing="0" width="100%" >
			    <thead>
			      <tr>
			      	<th>Sl no.</th>
			        <th>Contact name</th>
			        <th>Email</th>
					<th>Address</th>
					<th>Phone Number</th>
			      </tr>
			    </thead>
			
			    <tbody>
			      <% j= 0%>
			      <% @contact_name.each do |contact_name| %>
			      <tr class='clickable' data-location='<%= edit_contact_name_path(contact_name) %>'>
			      	<td> <%= j += 1%></td>
			        <td><%= contact_name.firstName.to_s.capitalize %> <%= contact_name.lastName.to_s.capitalize %></td>
					<td><%= contact_name.email %></td>
					<td>
						<table>
							<tr>
								<td>
									<%i=0%>
									<%contact_name.address_details.each do |address_detail| %>
										<%= i+=1%>.<%=h address_detail.address_text.to_s.capitalize%></br><%=address_detail.city_name.to_s.capitalize %>,<%=address_detail.state_name.to_s.capitalize %>,<%=address_detail.country_name.to_s.capitalize %></br> Pincode: <%=address_detail.pincode%></br>
									<% end %>
								</td>
							</tr>
						</table>
					</td>
					<td>
						<table>
							<tr>
								<td>
									<%k=0%>
									<%contact_name.phone_numbers.each do |phone_number| %>
										<%= k+=1%>.<%=h phone_number.contact_number%></br>
									<% end %>
								</td>
							</tr>
						</table>
					</td>
				  </tr>
			      <% end %>
			     </tbody>
		   </table>
		   <%= link_to 'Back', contact_names_path %>
		</div>
	</div>
</div>

  <% content_for(:extra_scripts) do %>


  <% end %>