config/routes.rb
Rails.application.routes.draw do
  #devise_for :models
  devise_for :users
  resources :phone_numbers
  resources :address_details
  resources :contact_names
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # LDAP OFF uncomment line blow
  #devise :database_authenticatable, :rememberable, :trackable, :registerable
  # LDAP ON uncomment line below:
  # devise :database_authenticatable, :ldap_authenticatable, :rememberable, :trackable
  #attr_accessor :login
  #after_create :assign_default_role

  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # set @user for specific method/actions
  before_action :set_user, only =>[edit,update]
  # ensure admin user for all method/actions
  before_action :ensure_admin

  # Breadcrumb navigation
  def set_breadcrumbs
    super
    add_breadcrumb 'User Admin', users_path
  end

  def index
    @users = User.all
  end
  
  def edit
    add_breadcrumb @user.username
    # cancancan ability class instance variable to check admin rights in edit
    @ability = Ability.new(@user)
  end

  def update
    ## IF User form updates correctly
    if (@user.update_attributes(user_params)) && (user_params[:admin] == '1')
      ## Redirect to user show action
      flash[:notice] = 'Admin role successfully added to user'
      # rolify add_role - adds row to user_roles table:
      @user.add_role 'admin'
      redirect_to(users_path(@user))
    elsif (@user.update_attributes(user_params)) && (user_params[:admin] == '0')
      flash[:notice] = 'Admin role successfully removed from user'
      # rolify remove_role - removes row from user_roles table
      @user.remove_role 'admin'
      redirect_to(users_path(@user))
    ## Update failed, display the edit form again to be fixed by user
    else
      render('edit')
    end
  end
  
  def sign_in
#     if user_signed_in?
#       redirect_to root_path
#     end
  end

  private

  def ensure_admin
    return if can? :manage, User
    flash[:error] = 'Not authorized to modify Users. Admin users only.'
    redirect_to root_path
  end

  def user_params
    params.require(:user).permit(:admin)
  end

  def set_user
    @user = User.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:error] = 'This action is not allowed.'
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% content_for(:page_header) do %>
Administration of User: <%= @user.username %>
<% end %>

<div class="user_edit">
  <%= form_for @user, url: user_path(@user), html: { method: :put } do |f| %>
    <%= error_messages_for(f.object) %>
    <div class="form-group" >
      <%= f.label :username, 'Username:' %><br>
      <%= f.text_field(:username, class: 'form-control', readonly: true) %>
    </div>

    <div class="form-group <%= f.object.errors[:fqdn].empty? ? "" : "has-error" %>">
      <%= f.label :email, 'Email:' %><br>
      <%= f.text_field(:email, class: 'form-control', readonly: true) %>
    </div>

    <%# if user is 'opca' make readonly....need at least one user that cannot be
    changed and is always 'admin', otherwise users could potentially lock
    themselves out with no 'admin' user on system %>
    <% if (@user.username == 'opca') && (@ability.can? :manage, :all)  %>
      <% flash[:warning] = "Admin user 'opca' cannot be edited." %>
      <div class="form-group <%= f.object.errors[:subnet].empty? ? "" : "has-error" %>">
        <%= f.label 'Admin:' %>
        <%= f.check_box :admin, {checked: true, disabled: true} %>
      </div>
    <%# if user is 'admin' and not the 'opca' user allow updates to remove 'admin' rights %>

    <% elsif (@user.username != 'opca') && (@ability.can? :manage, :all) %>
      <div class="form-group <%= f.object.errors[:subnet].empty? ? "" : "has-error" %>">
        <%= f.label 'Admin:' %>
        <%= f.check_box :admin, {checked: true} %>
      </div>
      <%# if user is not 'admin' allow updates to add 'admin' rights %>
    <% else %>
      <div class="form-group <%= f.object.errors[:subnet].empty? ? "" : "has-error" %>">
        <%= f.label 'Admin:' %>
        <%= f.check_box :admin, {checked: false} %>
      </div>
    <% end %>
</div>

    <% if @user.username != 'opca' %>
      <div class="form-buttons">
        <%= f.submit("Update User", class: "btn btn-primary") %>
      </div>
    <% end %>

  <% end %>

</div>

app/views/users/index.html.erb
<% content_for(:page_header) do %>
User Administration
<% end %>

  <table id="user_list" class="display table table-striped table-sm table-hover" cellspacing="0" width="100%" >
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th>Admin</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
      <tr class='clickable' data-location='<%= edit_user_path(user) %>'>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <%# check cancancan ability class for user: %>
        <% ability = Ability.new(user) %>
        <%# if user is admin; checkbox is checked but disabled. User has to click
        row to edit user %>
        <% if (ability.can? :manage, :all) %>
          <td><%= check_box_tag "admin", 1, true, disabled: true %></td>
        <%# if user is not admin: checkbox is unchecked and disabled. %>
        <% else %>
          <td><%= check_box_tag "admin", 1, false, disabled: true %></td>
        <% end %>
       </tr>
       <% end %>
     </tbody>
   </table>


  <% content_for(:extra_scripts) do %>

      $(document).ready(function() {
        $('#users').DataTable({ responsive:
          true<%= ', searching: false, paging: false, info: false' if @users.count <= 10 %>  });
      });

  <% end %>