config/routes.rb
Rails.application.routes.draw do
  #devise_for :models
  devise_for :users
  resources :phone_numbers
  resources :address_details
  resources :contact_names
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone_number.rb
class PhoneNumber < ApplicationRecord
  belongs_to :contact_name
  validates :contact_number, presence: true
end

app/controllers/phone_numbers_controller.rb
class PhoneNumbersController < ApplicationController
  before_action :set_phone_number, only: [:show, :edit, :update, :destroy]

  # GET /phone_numbers
  # GET /phone_numbers.json
  def index
    @phone_numbers = PhoneNumber.all
  end

  # GET /phone_numbers/1
  # GET /phone_numbers/1.json
  def show
  end

  # GET /phone_numbers/new
  def new
    @phone_number = PhoneNumber.new
  end

  # GET /phone_numbers/1/edit
  def edit
  end

  # POST /phone_numbers
  # POST /phone_numbers.json
  def create
    @phone_number = PhoneNumber.new(phone_number_params)

    respond_to do |format|
      if @phone_number.save
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully created.' }
        format.json { render :show, status: :created, location: @phone_number }
      else
        format.html { render :new }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /phone_numbers/1
  # PATCH/PUT /phone_numbers/1.json
  def update
    respond_to do |format|
      if @phone_number.update(phone_number_params)
        format.html { redirect_to @phone_number, notice: 'Phone number was successfully updated.' }
        format.json { render :show, status: :ok, location: @phone_number }
      else
        format.html { render :edit }
        format.json { render json: @phone_number.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /phone_numbers/1
  # DELETE /phone_numbers/1.json
  def destroy
    @phone_number.destroy
    respond_to do |format|
      format.html { redirect_to phone_numbers_url, notice: 'Phone number was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_phone_number
      @phone_number = PhoneNumber.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def phone_number_params
      params.require(:phone_number).permit(:contact_number)
    end
end

app/helpers/phone_numbers_helper.rb
module PhoneNumbersHelper
end

app/views/phone_numbers/_form.html.erb
<%= form_with(model: phone_number, local: true) do |form| %>
  <% if phone_number.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(phone_number.errors.count, "error") %> prohibited this phone_number from being saved:</h2>

      <ul>
      <% phone_number.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :contact_number %>
    <%= form.number_field :contact_number, id: :phone_number_contact_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/phone_numbers/edit.html.erb
<h1>Editing Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Show', @phone_number %> |
<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Phone Numbers</h1>

<table>
  <thead>
    <tr>
      <th>Contact number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @phone_numbers.each do |phone_number| %>
      <tr>
        <td><%= phone_number.contact_number %></td>
        <td><%= link_to 'Show', phone_number %></td>
        <td><%= link_to 'Edit', edit_phone_number_path(phone_number) %></td>
        <td><%= link_to 'Destroy', phone_number, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Phone Number', new_phone_number_path %>

app/views/phone_numbers/new.html.erb
<h1>New Phone Number</h1>

<%= render 'form', phone_number: @phone_number %>

<%= link_to 'Back', phone_numbers_path %>

app/views/phone_numbers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Contact number:</strong>
  <%= @phone_number.contact_number %>
</p>

<%= link_to 'Edit', edit_phone_number_path(@phone_number) %> |
<%= link_to 'Back', phone_numbers_path %>