config/routes.rb
Rails.application.routes.draw do
  #devise_for :models
  devise_for :users
  resources :phone_numbers
  resources :address_details
  resources :contact_names
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address_detail.rb
class AddressDetail < ApplicationRecord
  belongs_to :contact_name
  validates :address_text,:city_name,:state_name,:country_name, presence: true
end

app/controllers/address_details_controller.rb
class AddressDetailsController < ApplicationController
  before_action :set_address_detail, only: [:show, :edit, :update, :destroy]

  # GET /address_details
  # GET /address_details.json
  def index
    @address_details = AddressDetail.all
  end

  # GET /address_details/1
  # GET /address_details/1.json
  def show
  end

  # GET /address_details/new
  def new
    @address_detail = AddressDetail.new
  end

  # GET /address_details/1/edit
  def edit
  end

  # POST /address_details
  # POST /address_details.json
  def create
    @address_detail = AddressDetail.new(address_detail_params)

    respond_to do |format|
      if @address_detail.save
        format.html { redirect_to @address_detail, notice: 'Address detail was successfully created.' }
        format.json { render :show, status: :created, location: @address_detail }
      else
        format.html { render :new }
        format.json { render json: @address_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /address_details/1
  # PATCH/PUT /address_details/1.json
  def update
    respond_to do |format|
      if @address_detail.update(address_detail_params)
        format.html { redirect_to @address_detail, notice: 'Address detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @address_detail }
      else
        format.html { render :edit }
        format.json { render json: @address_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /address_details/1
  # DELETE /address_details/1.json
  def destroy
    @address_detail.destroy
    respond_to do |format|
      format.html { redirect_to address_details_url, notice: 'Address detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address_detail
      @address_detail = AddressDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_detail_params
      params.require(:address_detail).permit(:address1, :address2, :address3, :pincode)
    end
end

app/helpers/address_details_helper.rb
module AddressDetailsHelper
end

app/views/address_details/_form.html.erb
<%= form_with(model: address_detail, local: true) do |form| %>
  <% if address_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(address_detail.errors.count, "error") %> prohibited this address_detail from being saved:</h2>

      <ul>
      <% address_detail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1, id: :address_detail_address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2, id: :address_detail_address2 %>
  </div>

  <div class="field">
    <%= form.label :address3 %>
    <%= form.text_field :address3, id: :address_detail_address3 %>
  </div>

  <div class="field">
    <%= form.label :pincode %>
    <%= form.number_field :pincode, id: :address_detail_pincode %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/address_details/edit.html.erb
<h1>Editing Address Detail</h1>

<%= render 'form', address_detail: @address_detail %>

<%= link_to 'Show', @address_detail %> |
<%= link_to 'Back', address_details_path %>

app/views/address_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Address Details</h1>

<table>
  <thead>
    <tr>
      <th>Address1</th>
      <th>Address2</th>
      <th>Address3</th>
      <th>Pincode</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @address_details.each do |address_detail| %>
      <tr>
        <td><%= address_detail.address1 %></td>
        <td><%= address_detail.address2 %></td>
        <td><%= address_detail.address3 %></td>
        <td><%= address_detail.pincode %></td>
        <td><%= link_to 'Show', address_detail %></td>
        <td><%= link_to 'Edit', edit_address_detail_path(address_detail) %></td>
        <td><%= link_to 'Destroy', address_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Address Detail', new_address_detail_path %>

app/views/address_details/new.html.erb
<h1>New Address Detail</h1>

<%= render 'form', address_detail: @address_detail %>

<%= link_to 'Back', address_details_path %>

app/views/address_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address1:</strong>
  <%= @address_detail.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @address_detail.address2 %>
</p>

<p>
  <strong>Address3:</strong>
  <%= @address_detail.address3 %>
</p>

<p>
  <strong>Pincode:</strong>
  <%= @address_detail.pincode %>
</p>

<%= link_to 'Edit', edit_address_detail_path(@address_detail) %> |
<%= link_to 'Back', address_details_path %>